// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// AadUserConversationMember undocumented
type AadUserConversationMember struct {
	// ConversationMember is the base model of AadUserConversationMember
	ConversationMember
	// Email undocumented
	Email *string `json:"email,omitempty"`
	// UserID undocumented
	UserID *string `json:"userId,omitempty"`
	// User undocumented
	User *User `json:"user,omitempty"`
}
