// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// Identity undocumented
type Identity struct {
	// Object is the base model of Identity
	Object
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// ID undocumented
	ID *string `json:"id,omitempty"`
}

// IdentityContainer undocumented
type IdentityContainer struct {
	// Entity is the base model of IdentityContainer
	Entity
	// ConditionalAccess undocumented
	ConditionalAccess *ConditionalAccessRoot `json:"conditionalAccess,omitempty"`
}

// IdentityProvider undocumented
type IdentityProvider struct {
	// Entity is the base model of IdentityProvider
	Entity
	// ClientID undocumented
	ClientID *string `json:"clientId,omitempty"`
	// ClientSecret undocumented
	ClientSecret *string `json:"clientSecret,omitempty"`
	// Name undocumented
	Name *string `json:"name,omitempty"`
	// Type undocumented
	Type *string `json:"type,omitempty"`
}

// IdentitySecurityDefaultsEnforcementPolicy undocumented
type IdentitySecurityDefaultsEnforcementPolicy struct {
	// PolicyBase is the base model of IdentitySecurityDefaultsEnforcementPolicy
	PolicyBase
	// IsEnabled undocumented
	IsEnabled *bool `json:"isEnabled,omitempty"`
}

// IdentitySet undocumented
type IdentitySet struct {
	// Object is the base model of IdentitySet
	Object
	// Application undocumented
	Application *Identity `json:"application,omitempty"`
	// Device undocumented
	Device *Identity `json:"device,omitempty"`
	// User undocumented
	User *Identity `json:"user,omitempty"`
}
