// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import (
	"context"
	"fmt"
	"io/ioutil"
	"net/http"

	"github.com/codecutteruk/msgraph.go/jsonx"
)

// ApplicationSignInDetailedSummary returns request builder for ApplicationSignInDetailedSummary collection
func (b *ReportRootRequestBuilder) ApplicationSignInDetailedSummary() *ReportRootApplicationSignInDetailedSummaryCollectionRequestBuilder {
	bb := &ReportRootApplicationSignInDetailedSummaryCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/applicationSignInDetailedSummary"
	return bb
}

// ReportRootApplicationSignInDetailedSummaryCollectionRequestBuilder is request builder for ApplicationSignInDetailedSummary collection
type ReportRootApplicationSignInDetailedSummaryCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for ApplicationSignInDetailedSummary collection
func (b *ReportRootApplicationSignInDetailedSummaryCollectionRequestBuilder) Request() *ReportRootApplicationSignInDetailedSummaryCollectionRequest {
	return &ReportRootApplicationSignInDetailedSummaryCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for ApplicationSignInDetailedSummary item
func (b *ReportRootApplicationSignInDetailedSummaryCollectionRequestBuilder) ID(id string) *ApplicationSignInDetailedSummaryRequestBuilder {
	bb := &ApplicationSignInDetailedSummaryRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ReportRootApplicationSignInDetailedSummaryCollectionRequest is request for ApplicationSignInDetailedSummary collection
type ReportRootApplicationSignInDetailedSummaryCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for ApplicationSignInDetailedSummary collection
func (r *ReportRootApplicationSignInDetailedSummaryCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]ApplicationSignInDetailedSummary, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []ApplicationSignInDetailedSummary
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []ApplicationSignInDetailedSummary
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for ApplicationSignInDetailedSummary collection, max N pages
func (r *ReportRootApplicationSignInDetailedSummaryCollectionRequest) GetN(ctx context.Context, n int) ([]ApplicationSignInDetailedSummary, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for ApplicationSignInDetailedSummary collection
func (r *ReportRootApplicationSignInDetailedSummaryCollectionRequest) Get(ctx context.Context) ([]ApplicationSignInDetailedSummary, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for ApplicationSignInDetailedSummary collection
func (r *ReportRootApplicationSignInDetailedSummaryCollectionRequest) Add(ctx context.Context, reqObj *ApplicationSignInDetailedSummary) (resObj *ApplicationSignInDetailedSummary, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// AuthenticationMethods is navigation property
func (b *ReportRootRequestBuilder) AuthenticationMethods() *AuthenticationMethodsRootRequestBuilder {
	bb := &AuthenticationMethodsRootRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/authenticationMethods"
	return bb
}

// CredentialUserRegistrationDetails returns request builder for CredentialUserRegistrationDetails collection
func (b *ReportRootRequestBuilder) CredentialUserRegistrationDetails() *ReportRootCredentialUserRegistrationDetailsCollectionRequestBuilder {
	bb := &ReportRootCredentialUserRegistrationDetailsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/credentialUserRegistrationDetails"
	return bb
}

// ReportRootCredentialUserRegistrationDetailsCollectionRequestBuilder is request builder for CredentialUserRegistrationDetails collection
type ReportRootCredentialUserRegistrationDetailsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for CredentialUserRegistrationDetails collection
func (b *ReportRootCredentialUserRegistrationDetailsCollectionRequestBuilder) Request() *ReportRootCredentialUserRegistrationDetailsCollectionRequest {
	return &ReportRootCredentialUserRegistrationDetailsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for CredentialUserRegistrationDetails item
func (b *ReportRootCredentialUserRegistrationDetailsCollectionRequestBuilder) ID(id string) *CredentialUserRegistrationDetailsRequestBuilder {
	bb := &CredentialUserRegistrationDetailsRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ReportRootCredentialUserRegistrationDetailsCollectionRequest is request for CredentialUserRegistrationDetails collection
type ReportRootCredentialUserRegistrationDetailsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for CredentialUserRegistrationDetails collection
func (r *ReportRootCredentialUserRegistrationDetailsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]CredentialUserRegistrationDetails, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []CredentialUserRegistrationDetails
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []CredentialUserRegistrationDetails
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for CredentialUserRegistrationDetails collection, max N pages
func (r *ReportRootCredentialUserRegistrationDetailsCollectionRequest) GetN(ctx context.Context, n int) ([]CredentialUserRegistrationDetails, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for CredentialUserRegistrationDetails collection
func (r *ReportRootCredentialUserRegistrationDetailsCollectionRequest) Get(ctx context.Context) ([]CredentialUserRegistrationDetails, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for CredentialUserRegistrationDetails collection
func (r *ReportRootCredentialUserRegistrationDetailsCollectionRequest) Add(ctx context.Context, reqObj *CredentialUserRegistrationDetails) (resObj *CredentialUserRegistrationDetails, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// DailyPrintUsageSummariesByPrinter returns request builder for PrintUsageSummaryByPrinter collection
func (b *ReportRootRequestBuilder) DailyPrintUsageSummariesByPrinter() *ReportRootDailyPrintUsageSummariesByPrinterCollectionRequestBuilder {
	bb := &ReportRootDailyPrintUsageSummariesByPrinterCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/dailyPrintUsageSummariesByPrinter"
	return bb
}

// ReportRootDailyPrintUsageSummariesByPrinterCollectionRequestBuilder is request builder for PrintUsageSummaryByPrinter collection
type ReportRootDailyPrintUsageSummariesByPrinterCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for PrintUsageSummaryByPrinter collection
func (b *ReportRootDailyPrintUsageSummariesByPrinterCollectionRequestBuilder) Request() *ReportRootDailyPrintUsageSummariesByPrinterCollectionRequest {
	return &ReportRootDailyPrintUsageSummariesByPrinterCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for PrintUsageSummaryByPrinter item
func (b *ReportRootDailyPrintUsageSummariesByPrinterCollectionRequestBuilder) ID(id string) *PrintUsageSummaryByPrinterRequestBuilder {
	bb := &PrintUsageSummaryByPrinterRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ReportRootDailyPrintUsageSummariesByPrinterCollectionRequest is request for PrintUsageSummaryByPrinter collection
type ReportRootDailyPrintUsageSummariesByPrinterCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for PrintUsageSummaryByPrinter collection
func (r *ReportRootDailyPrintUsageSummariesByPrinterCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]PrintUsageSummaryByPrinter, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []PrintUsageSummaryByPrinter
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []PrintUsageSummaryByPrinter
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for PrintUsageSummaryByPrinter collection, max N pages
func (r *ReportRootDailyPrintUsageSummariesByPrinterCollectionRequest) GetN(ctx context.Context, n int) ([]PrintUsageSummaryByPrinter, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for PrintUsageSummaryByPrinter collection
func (r *ReportRootDailyPrintUsageSummariesByPrinterCollectionRequest) Get(ctx context.Context) ([]PrintUsageSummaryByPrinter, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for PrintUsageSummaryByPrinter collection
func (r *ReportRootDailyPrintUsageSummariesByPrinterCollectionRequest) Add(ctx context.Context, reqObj *PrintUsageSummaryByPrinter) (resObj *PrintUsageSummaryByPrinter, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// DailyPrintUsageSummariesByUser returns request builder for PrintUsageSummaryByUser collection
func (b *ReportRootRequestBuilder) DailyPrintUsageSummariesByUser() *ReportRootDailyPrintUsageSummariesByUserCollectionRequestBuilder {
	bb := &ReportRootDailyPrintUsageSummariesByUserCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/dailyPrintUsageSummariesByUser"
	return bb
}

// ReportRootDailyPrintUsageSummariesByUserCollectionRequestBuilder is request builder for PrintUsageSummaryByUser collection
type ReportRootDailyPrintUsageSummariesByUserCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for PrintUsageSummaryByUser collection
func (b *ReportRootDailyPrintUsageSummariesByUserCollectionRequestBuilder) Request() *ReportRootDailyPrintUsageSummariesByUserCollectionRequest {
	return &ReportRootDailyPrintUsageSummariesByUserCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for PrintUsageSummaryByUser item
func (b *ReportRootDailyPrintUsageSummariesByUserCollectionRequestBuilder) ID(id string) *PrintUsageSummaryByUserRequestBuilder {
	bb := &PrintUsageSummaryByUserRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ReportRootDailyPrintUsageSummariesByUserCollectionRequest is request for PrintUsageSummaryByUser collection
type ReportRootDailyPrintUsageSummariesByUserCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for PrintUsageSummaryByUser collection
func (r *ReportRootDailyPrintUsageSummariesByUserCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]PrintUsageSummaryByUser, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []PrintUsageSummaryByUser
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []PrintUsageSummaryByUser
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for PrintUsageSummaryByUser collection, max N pages
func (r *ReportRootDailyPrintUsageSummariesByUserCollectionRequest) GetN(ctx context.Context, n int) ([]PrintUsageSummaryByUser, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for PrintUsageSummaryByUser collection
func (r *ReportRootDailyPrintUsageSummariesByUserCollectionRequest) Get(ctx context.Context) ([]PrintUsageSummaryByUser, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for PrintUsageSummaryByUser collection
func (r *ReportRootDailyPrintUsageSummariesByUserCollectionRequest) Add(ctx context.Context, reqObj *PrintUsageSummaryByUser) (resObj *PrintUsageSummaryByUser, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// MonthlyPrintUsageSummariesByPrinter returns request builder for PrintUsageSummaryByPrinter collection
func (b *ReportRootRequestBuilder) MonthlyPrintUsageSummariesByPrinter() *ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequestBuilder {
	bb := &ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/monthlyPrintUsageSummariesByPrinter"
	return bb
}

// ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequestBuilder is request builder for PrintUsageSummaryByPrinter collection
type ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for PrintUsageSummaryByPrinter collection
func (b *ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequestBuilder) Request() *ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequest {
	return &ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for PrintUsageSummaryByPrinter item
func (b *ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequestBuilder) ID(id string) *PrintUsageSummaryByPrinterRequestBuilder {
	bb := &PrintUsageSummaryByPrinterRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequest is request for PrintUsageSummaryByPrinter collection
type ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for PrintUsageSummaryByPrinter collection
func (r *ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]PrintUsageSummaryByPrinter, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []PrintUsageSummaryByPrinter
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []PrintUsageSummaryByPrinter
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for PrintUsageSummaryByPrinter collection, max N pages
func (r *ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequest) GetN(ctx context.Context, n int) ([]PrintUsageSummaryByPrinter, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for PrintUsageSummaryByPrinter collection
func (r *ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequest) Get(ctx context.Context) ([]PrintUsageSummaryByPrinter, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for PrintUsageSummaryByPrinter collection
func (r *ReportRootMonthlyPrintUsageSummariesByPrinterCollectionRequest) Add(ctx context.Context, reqObj *PrintUsageSummaryByPrinter) (resObj *PrintUsageSummaryByPrinter, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// MonthlyPrintUsageSummariesByUser returns request builder for PrintUsageSummaryByUser collection
func (b *ReportRootRequestBuilder) MonthlyPrintUsageSummariesByUser() *ReportRootMonthlyPrintUsageSummariesByUserCollectionRequestBuilder {
	bb := &ReportRootMonthlyPrintUsageSummariesByUserCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/monthlyPrintUsageSummariesByUser"
	return bb
}

// ReportRootMonthlyPrintUsageSummariesByUserCollectionRequestBuilder is request builder for PrintUsageSummaryByUser collection
type ReportRootMonthlyPrintUsageSummariesByUserCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for PrintUsageSummaryByUser collection
func (b *ReportRootMonthlyPrintUsageSummariesByUserCollectionRequestBuilder) Request() *ReportRootMonthlyPrintUsageSummariesByUserCollectionRequest {
	return &ReportRootMonthlyPrintUsageSummariesByUserCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for PrintUsageSummaryByUser item
func (b *ReportRootMonthlyPrintUsageSummariesByUserCollectionRequestBuilder) ID(id string) *PrintUsageSummaryByUserRequestBuilder {
	bb := &PrintUsageSummaryByUserRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ReportRootMonthlyPrintUsageSummariesByUserCollectionRequest is request for PrintUsageSummaryByUser collection
type ReportRootMonthlyPrintUsageSummariesByUserCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for PrintUsageSummaryByUser collection
func (r *ReportRootMonthlyPrintUsageSummariesByUserCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]PrintUsageSummaryByUser, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []PrintUsageSummaryByUser
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []PrintUsageSummaryByUser
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for PrintUsageSummaryByUser collection, max N pages
func (r *ReportRootMonthlyPrintUsageSummariesByUserCollectionRequest) GetN(ctx context.Context, n int) ([]PrintUsageSummaryByUser, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for PrintUsageSummaryByUser collection
func (r *ReportRootMonthlyPrintUsageSummariesByUserCollectionRequest) Get(ctx context.Context) ([]PrintUsageSummaryByUser, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for PrintUsageSummaryByUser collection
func (r *ReportRootMonthlyPrintUsageSummariesByUserCollectionRequest) Add(ctx context.Context, reqObj *PrintUsageSummaryByUser) (resObj *PrintUsageSummaryByUser, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}

// UserCredentialUsageDetails returns request builder for UserCredentialUsageDetails collection
func (b *ReportRootRequestBuilder) UserCredentialUsageDetails() *ReportRootUserCredentialUsageDetailsCollectionRequestBuilder {
	bb := &ReportRootUserCredentialUsageDetailsCollectionRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/userCredentialUsageDetails"
	return bb
}

// ReportRootUserCredentialUsageDetailsCollectionRequestBuilder is request builder for UserCredentialUsageDetails collection
type ReportRootUserCredentialUsageDetailsCollectionRequestBuilder struct{ BaseRequestBuilder }

// Request returns request for UserCredentialUsageDetails collection
func (b *ReportRootUserCredentialUsageDetailsCollectionRequestBuilder) Request() *ReportRootUserCredentialUsageDetailsCollectionRequest {
	return &ReportRootUserCredentialUsageDetailsCollectionRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// ID returns request builder for UserCredentialUsageDetails item
func (b *ReportRootUserCredentialUsageDetailsCollectionRequestBuilder) ID(id string) *UserCredentialUsageDetailsRequestBuilder {
	bb := &UserCredentialUsageDetailsRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.baseURL += "/" + id
	return bb
}

// ReportRootUserCredentialUsageDetailsCollectionRequest is request for UserCredentialUsageDetails collection
type ReportRootUserCredentialUsageDetailsCollectionRequest struct{ BaseRequest }

// Paging perfoms paging operation for UserCredentialUsageDetails collection
func (r *ReportRootUserCredentialUsageDetailsCollectionRequest) Paging(ctx context.Context, method, path string, obj interface{}, n int) ([]UserCredentialUsageDetails, error) {
	req, err := r.NewJSONRequest(method, path, obj)
	if err != nil {
		return nil, err
	}
	if ctx != nil {
		req = req.WithContext(ctx)
	}
	res, err := r.client.Do(req)
	if err != nil {
		return nil, err
	}
	var values []UserCredentialUsageDetails
	for {
		if res.StatusCode != http.StatusOK {
			b, _ := ioutil.ReadAll(res.Body)
			res.Body.Close()
			errRes := &ErrorResponse{Response: res}
			err := jsonx.Unmarshal(b, errRes)
			if err != nil {
				return nil, fmt.Errorf("%s: %s", res.Status, string(b))
			}
			return nil, errRes
		}
		var (
			paging Paging
			value  []UserCredentialUsageDetails
		)
		err := jsonx.NewDecoder(res.Body).Decode(&paging)
		res.Body.Close()
		if err != nil {
			return nil, err
		}
		err = jsonx.Unmarshal(paging.Value, &value)
		if err != nil {
			return nil, err
		}
		values = append(values, value...)
		if n >= 0 {
			n--
		}
		if n == 0 || len(paging.NextLink) == 0 {
			return values, nil
		}
		req, err = http.NewRequest("GET", paging.NextLink, nil)
		if ctx != nil {
			req = req.WithContext(ctx)
		}
		res, err = r.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
}

// GetN performs GET request for UserCredentialUsageDetails collection, max N pages
func (r *ReportRootUserCredentialUsageDetailsCollectionRequest) GetN(ctx context.Context, n int) ([]UserCredentialUsageDetails, error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	return r.Paging(ctx, "GET", query, nil, n)
}

// Get performs GET request for UserCredentialUsageDetails collection
func (r *ReportRootUserCredentialUsageDetailsCollectionRequest) Get(ctx context.Context) ([]UserCredentialUsageDetails, error) {
	return r.GetN(ctx, 0)
}

// Add performs POST request for UserCredentialUsageDetails collection
func (r *ReportRootUserCredentialUsageDetailsCollectionRequest) Add(ctx context.Context, reqObj *UserCredentialUsageDetails) (resObj *UserCredentialUsageDetails, err error) {
	err = r.JSONRequest(ctx, "POST", "", reqObj, &resObj)
	return
}
