// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// StagedFeatureName undocumented
type StagedFeatureName string

const (
	// StagedFeatureNameVPassthroughAuthentication undocumented
	StagedFeatureNameVPassthroughAuthentication StagedFeatureName = "passthroughAuthentication"
	// StagedFeatureNameVSeamlessSso undocumented
	StagedFeatureNameVSeamlessSso StagedFeatureName = "seamlessSso"
	// StagedFeatureNameVPasswordHashSync undocumented
	StagedFeatureNameVPasswordHashSync StagedFeatureName = "passwordHashSync"
	// StagedFeatureNameVUnknownFutureValue undocumented
	StagedFeatureNameVUnknownFutureValue StagedFeatureName = "unknownFutureValue"
	// StagedFeatureNameVEmailAsAlternateID undocumented
	StagedFeatureNameVEmailAsAlternateID StagedFeatureName = "emailAsAlternateId"
)

var (
	// StagedFeatureNamePPassthroughAuthentication is a pointer to StagedFeatureNameVPassthroughAuthentication
	StagedFeatureNamePPassthroughAuthentication = &_StagedFeatureNamePPassthroughAuthentication
	// StagedFeatureNamePSeamlessSso is a pointer to StagedFeatureNameVSeamlessSso
	StagedFeatureNamePSeamlessSso = &_StagedFeatureNamePSeamlessSso
	// StagedFeatureNamePPasswordHashSync is a pointer to StagedFeatureNameVPasswordHashSync
	StagedFeatureNamePPasswordHashSync = &_StagedFeatureNamePPasswordHashSync
	// StagedFeatureNamePUnknownFutureValue is a pointer to StagedFeatureNameVUnknownFutureValue
	StagedFeatureNamePUnknownFutureValue = &_StagedFeatureNamePUnknownFutureValue
	// StagedFeatureNamePEmailAsAlternateID is a pointer to StagedFeatureNameVEmailAsAlternateID
	StagedFeatureNamePEmailAsAlternateID = &_StagedFeatureNamePEmailAsAlternateID
)

var (
	_StagedFeatureNamePPassthroughAuthentication = StagedFeatureNameVPassthroughAuthentication
	_StagedFeatureNamePSeamlessSso               = StagedFeatureNameVSeamlessSso
	_StagedFeatureNamePPasswordHashSync          = StagedFeatureNameVPasswordHashSync
	_StagedFeatureNamePUnknownFutureValue        = StagedFeatureNameVUnknownFutureValue
	_StagedFeatureNamePEmailAsAlternateID        = StagedFeatureNameVEmailAsAlternateID
)
