// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// TeamworkActivityTopicSource undocumented
type TeamworkActivityTopicSource string

const (
	// TeamworkActivityTopicSourceVEntityURL undocumented
	TeamworkActivityTopicSourceVEntityURL TeamworkActivityTopicSource = "entityUrl"
	// TeamworkActivityTopicSourceVText undocumented
	TeamworkActivityTopicSourceVText TeamworkActivityTopicSource = "text"
)

var (
	// TeamworkActivityTopicSourcePEntityURL is a pointer to TeamworkActivityTopicSourceVEntityURL
	TeamworkActivityTopicSourcePEntityURL = &_TeamworkActivityTopicSourcePEntityURL
	// TeamworkActivityTopicSourcePText is a pointer to TeamworkActivityTopicSourceVText
	TeamworkActivityTopicSourcePText = &_TeamworkActivityTopicSourcePText
)

var (
	_TeamworkActivityTopicSourcePEntityURL = TeamworkActivityTopicSourceVEntityURL
	_TeamworkActivityTopicSourcePText      = TeamworkActivityTopicSourceVText
)

// TeamworkTagType undocumented
type TeamworkTagType string

const (
	// TeamworkTagTypeVStandard undocumented
	TeamworkTagTypeVStandard TeamworkTagType = "standard"
)

var (
	// TeamworkTagTypePStandard is a pointer to TeamworkTagTypeVStandard
	TeamworkTagTypePStandard = &_TeamworkTagTypePStandard
)

var (
	_TeamworkTagTypePStandard = TeamworkTagTypeVStandard
)
