// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// RequestObject undocumented
type RequestObject struct {
	// Entity is the base model of RequestObject
	Entity
	// Approval undocumented
	Approval *Approval `json:"approval,omitempty"`
}

// RequestSchedule undocumented
type RequestSchedule struct {
	// Object is the base model of RequestSchedule
	Object
	// Expiration undocumented
	Expiration *ExpirationPattern `json:"expiration,omitempty"`
	// Recurrence undocumented
	Recurrence *PatternedRecurrence `json:"recurrence,omitempty"`
	// StartDateTime undocumented
	StartDateTime *time.Time `json:"startDateTime,omitempty"`
}
