// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// Channel undocumented
type Channel struct {
	// Entity is the base model of Channel
	Entity
	// CreatedDateTime undocumented
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// Email undocumented
	Email *string `json:"email,omitempty"`
	// IsFavoriteByDefault undocumented
	IsFavoriteByDefault *bool `json:"isFavoriteByDefault,omitempty"`
	// MembershipType undocumented
	MembershipType *ChannelMembershipType `json:"membershipType,omitempty"`
	// ModerationSettings undocumented
	ModerationSettings *ChannelModerationSettings `json:"moderationSettings,omitempty"`
	// WebURL undocumented
	WebURL *string `json:"webUrl,omitempty"`
	// FilesFolder undocumented
	FilesFolder *DriveItem `json:"filesFolder,omitempty"`
	// Members undocumented
	Members []ConversationMember `json:"members,omitempty"`
	// Messages undocumented
	Messages []ChatMessage `json:"messages,omitempty"`
	// Tabs undocumented
	Tabs []TeamsTab `json:"tabs,omitempty"`
}

// ChannelIdentity undocumented
type ChannelIdentity struct {
	// Object is the base model of ChannelIdentity
	Object
	// ChannelID undocumented
	ChannelID *string `json:"channelId,omitempty"`
	// TeamID undocumented
	TeamID *string `json:"teamId,omitempty"`
}

// ChannelModerationSettings undocumented
type ChannelModerationSettings struct {
	// Object is the base model of ChannelModerationSettings
	Object
	// AllowNewMessageFromBots undocumented
	AllowNewMessageFromBots *bool `json:"allowNewMessageFromBots,omitempty"`
	// AllowNewMessageFromConnectors undocumented
	AllowNewMessageFromConnectors *bool `json:"allowNewMessageFromConnectors,omitempty"`
	// ReplyRestriction undocumented
	ReplyRestriction *ReplyRestriction `json:"replyRestriction,omitempty"`
	// UserNewMessageRestriction undocumented
	UserNewMessageRestriction *UserNewMessageRestriction `json:"userNewMessageRestriction,omitempty"`
}
