// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// Report Device Configuration profile History reports.
type Report struct {
	// Object is the base model of Report
	Object
	// Content undocumented
	Content *Stream `json:"content,omitempty"`
}

// ReportRoot The resource that represents an instance of Enrollment Failure Reports.
type ReportRoot struct {
	// Entity is the base model of ReportRoot
	Entity
	// ApplicationSignInDetailedSummary undocumented
	ApplicationSignInDetailedSummary []ApplicationSignInDetailedSummary `json:"applicationSignInDetailedSummary,omitempty"`
	// AuthenticationMethods undocumented
	AuthenticationMethods *AuthenticationMethodsRoot `json:"authenticationMethods,omitempty"`
	// CredentialUserRegistrationDetails undocumented
	CredentialUserRegistrationDetails []CredentialUserRegistrationDetails `json:"credentialUserRegistrationDetails,omitempty"`
	// UserCredentialUsageDetails undocumented
	UserCredentialUsageDetails []UserCredentialUsageDetails `json:"userCredentialUsageDetails,omitempty"`
	// DailyPrintUsageSummariesByPrinter undocumented
	DailyPrintUsageSummariesByPrinter []PrintUsageSummaryByPrinter `json:"dailyPrintUsageSummariesByPrinter,omitempty"`
	// DailyPrintUsageSummariesByUser undocumented
	DailyPrintUsageSummariesByUser []PrintUsageSummaryByUser `json:"dailyPrintUsageSummariesByUser,omitempty"`
	// MonthlyPrintUsageSummariesByPrinter undocumented
	MonthlyPrintUsageSummariesByPrinter []PrintUsageSummaryByPrinter `json:"monthlyPrintUsageSummariesByPrinter,omitempty"`
	// MonthlyPrintUsageSummariesByUser undocumented
	MonthlyPrintUsageSummariesByUser []PrintUsageSummaryByUser `json:"monthlyPrintUsageSummariesByUser,omitempty"`
}
