// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// InnerErrorDetail undocumented
type InnerErrorDetail struct {
	// Object is the base model of InnerErrorDetail
	Object
	// Message undocumented
	Message *string `json:"message,omitempty"`
	// Source undocumented
	Source *string `json:"source,omitempty"`
}
