// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "time"

// ProvisioningObjectSummary undocumented
type ProvisioningObjectSummary struct {
	// Entity is the base model of ProvisioningObjectSummary
	Entity
	// Action undocumented
	Action *string `json:"action,omitempty"`
	// ActivityDateTime undocumented
	ActivityDateTime *time.Time `json:"activityDateTime,omitempty"`
	// ChangeID undocumented
	ChangeID *string `json:"changeId,omitempty"`
	// CycleID undocumented
	CycleID *string `json:"cycleId,omitempty"`
	// DurationInMilliseconds undocumented
	DurationInMilliseconds *int `json:"durationInMilliseconds,omitempty"`
	// InitiatedBy undocumented
	InitiatedBy *Initiator `json:"initiatedBy,omitempty"`
	// JobID undocumented
	JobID *string `json:"jobId,omitempty"`
	// ModifiedProperties undocumented
	ModifiedProperties []ModifiedProperty `json:"modifiedProperties,omitempty"`
	// ProvisioningSteps undocumented
	ProvisioningSteps []ProvisioningStep `json:"provisioningSteps,omitempty"`
	// ServicePrincipal undocumented
	ServicePrincipal *ProvisioningServicePrincipal `json:"servicePrincipal,omitempty"`
	// SourceIdentity undocumented
	SourceIdentity *ProvisionedIdentity `json:"sourceIdentity,omitempty"`
	// SourceSystem undocumented
	SourceSystem *ProvisioningSystemDetails `json:"sourceSystem,omitempty"`
	// StatusInfo undocumented
	StatusInfo *StatusBase `json:"statusInfo,omitempty"`
	// TargetIdentity undocumented
	TargetIdentity *ProvisionedIdentity `json:"targetIdentity,omitempty"`
	// TargetSystem undocumented
	TargetSystem *ProvisioningSystemDetails `json:"targetSystem,omitempty"`
	// TenantID undocumented
	TenantID *string `json:"tenantId,omitempty"`
}

// ProvisioningServicePrincipal undocumented
type ProvisioningServicePrincipal struct {
	// Identity is the base model of ProvisioningServicePrincipal
	Identity
}

// ProvisioningStep undocumented
type ProvisioningStep struct {
	// Object is the base model of ProvisioningStep
	Object
	// Description undocumented
	Description *string `json:"description,omitempty"`
	// Details undocumented
	Details *DetailsInfo `json:"details,omitempty"`
	// Name undocumented
	Name *string `json:"name,omitempty"`
	// ProvisioningStepType undocumented
	ProvisioningStepType *ProvisioningStepType `json:"provisioningStepType,omitempty"`
	// Status undocumented
	Status *ProvisioningResult `json:"status,omitempty"`
}

// ProvisioningSystemDetails undocumented
type ProvisioningSystemDetails struct {
	// Object is the base model of ProvisioningSystemDetails
	Object
	// Details undocumented
	Details *DetailsInfo `json:"details,omitempty"`
	// DisplayName undocumented
	DisplayName *string `json:"displayName,omitempty"`
	// ID undocumented
	ID *string `json:"id,omitempty"`
}
