// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

// PrivateLinkResourcePolicy undocumented
type PrivateLinkResourcePolicy struct {
	// Entity is the base model of PrivateLinkResourcePolicy
	Entity
	// ExternalPrivateLinkID undocumented
	ExternalPrivateLinkID *string `json:"externalPrivateLinkId,omitempty"`
	// TenantApprovals undocumented
	TenantApprovals []TenantApprovals `json:"tenantApprovals,omitempty"`
}
