// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

// TermStoreRequestBuilder is request builder for TermStore
type TermStoreRequestBuilder struct{ BaseRequestBuilder }

// Request returns TermStoreRequest
func (b *TermStoreRequestBuilder) Request() *TermStoreRequest {
	return &TermStoreRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client},
	}
}

// TermStoreRequest is request for TermStore
type TermStoreRequest struct{ BaseRequest }

// Get performs GET request for TermStore
func (r *TermStoreRequest) Get(ctx context.Context) (resObj *TermStore, err error) {
	var query string
	if r.query != nil {
		query = "?" + r.query.Encode()
	}
	err = r.JSONRequest(ctx, "GET", query, nil, &resObj)
	return
}

// Update performs PATCH request for TermStore
func (r *TermStoreRequest) Update(ctx context.Context, reqObj *TermStore) error {
	return r.JSONRequest(ctx, "PATCH", "", reqObj, nil)
}

// Delete performs DELETE request for TermStore
func (r *TermStoreRequest) Delete(ctx context.Context) error {
	return r.JSONRequest(ctx, "DELETE", "", nil, nil)
}
