---
name: go generate test
on: [push]

jobs:
  go-generate-test:
    name: go generate test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - run: go test -v ./gen ./jsonx
      - run: go generate ./gen
      - run: go get ./cmd/msgraph-me
      - run: go get ./cmd/msgraph-usergroup
      - run: go get ./cmd/msgraph-sshpubkey
      - run: go get ./cmd/msgraph-spoget
